[package]
name = "hand"
version = "0.1.0"
edition = "2021"
publish = false

[lib]
crate-type = ["cdylib", "lib"]

[lints.rust]
unexpected_cfgs = { level = "warn", check-cfg = [
    'cfg(target_os, values("solana"))',
] }


[dependencies]
borsh = "1.5"
bytemuck = "1.21.0"
podded = "0.5.2"
typhoon = { path = "../../../../crates/lib", features = ["borsh"] }
