[package]
name = "hand"
version = "0.1.0"
edition = "2021"
publish = false

[lib]
crate-type = ["cdylib", "lib"]

[features]
default = ["solana-nostd-entrypoint", "solana-program"]
pinocchio = ["dep:pinocchio", "typhoon/pinocchio"]

[dependencies]
borsh = "1.5"
bytemuck = "1.21.0"
pinocchio = { git = "https://github.com/febo/pinocchio", optional = true }
podded = "0.5.2"
solana-nostd-entrypoint = { git = "https://github.com/cavemanloverboy/solana-nostd-entrypoint", optional = true }
solana-program = { version = "1.18", optional = true }
typhoon = { path = "../../../../crates/lib", features = ["borsh"] }
