[package]
name = "hand"
version = "0.1.0"
edition = "2021"
publish = false

[features]
logging = []

[lib]
crate-type = ["cdylib", "lib"]

[lints.rust]
unexpected_cfgs = { level = "warn", check-cfg = [
    'cfg(target_os, values("solana"))',
] }


[dependencies]
borsh = { version = "1.5", features = ["derive"], default-features = false }
bytemuck = { version = "1.21.0", features = ["min_const_generics"] }
typhoon = { path = "../../../../crates/lib", features = ["borsh"] }
