[package]
name = "typhoon-idl-generator"
version.workspace = true
rust-version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true
repository.workspace = true

[dependencies]
typhoon-metadata-extractor.workspace = true
