[package]
name = "typhoon-idl-generator"
description = "TODO"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true
repository.workspace = true

[dependencies]
typhoon-metadata-extractor.workspace = true
