[package]
name = "typhoon-space"
version.workspace = true
rust-version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true
repository.workspace = true

[dependencies]
typhoon-program.workspace = true
typhoon-space-macro.workspace = true
