[package]
name = "typhoon-types"
version.workspace = true
rust-version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true
repository.workspace = true

[dependencies]
typhoon-program.workspace = true
zerocopy = { workspace = true, features = ["derive"] }
