name: Lints

on:
  pull_request:
    branches: ["main"]

env:
  RUSTFLAGS: "-Dwarnings"

jobs:
  run_cargo_checks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install protobuf compiler # delete this once we get to solana 2.1
        run: sudo apt-get install protobuf-compiler
      - name: Rustup install nightly
        run: rustup toolchain install nightly
      - name: Rustup install rustfmt
        run: rustup component add rustfmt --toolchain nightly
      - name: Run Cargo fmt
        run: cargo +nightly fmt --all -- --check
      - name: Run Cargo clippy
        run: cargo clippy --all-targets --all-features